### ISSUE TITLE
Remove (stack-depth d0) in init when no stack

### ISSUE THREAD

**Issue by ssardina** [bonetblai/qnp2fond#3]
As discussed by email, when the translator realizes no stack is needed, no stack is modeled in the domain but the predicate `(stack-depth d0)` is still set in `:init` in the planning problem file. 

I guess that needs not to be entered, the fluent is not defined when no stack is modeled. 

Just wanted to leave it here for the records (email gets lost.... )

**Comment by bonetblai** [comment]
Fixed and also that when direct translation is used not predicates for boolean features are defined.
